"""On-the-fly synthetic dataset generation on the CPU, wrapped as an infinite DataLoader."""
import os

import numpy as np
import torch
from numpy.random import randint
from torch.utils.data import DataLoader, IterableDataset

from .config import DataConfig
from .prior import rand_cat_sizes, rand_dataset_filtered, rand_dataset_plain, randlogint


class PriorDataset(IterableDataset):
    """Yields micro-batches (x, y, n_train) with x: (micro_batch_size, n_rows, n_features), y: (micro_batch_size, n_rows).
    Rows [:n_train] are the training rows. Class labels are stored as floats."""

    def __init__(self, cfg: DataConfig):
        self.cfg = cfg
        self.regression = cfg.task == "regression"

    def __iter__(self):
        while True:  # numpy arrays are sent to the main process by value, avoiding shared-memory limits of containers
            x, y, n_train = self.sample_batch()
            yield x.numpy(), y.numpy(), n_train

    def sample_batch(self) -> tuple[torch.Tensor, torch.Tensor, int]:
        cfg = self.cfg
        n_rows = rand_size(cfg.min_seq_len, cfg.max_seq_len, cfg.log_seq_len)
        n_train = int(np.clip(n_rows * np.random.uniform(cfg.min_train_frac, cfg.max_train_frac), 1, n_rows - 1))
        n_features = rand_size(cfg.min_features, cfg.max_features, cfg.log_n_features)
        xs, ys = zip(*[self.sample_dataset(n_rows, n_train, n_features) for _ in range(cfg.micro_batch_size)])
        return torch.stack(xs), torch.stack(ys), n_train

    def sample_dataset(self, n_rows: int, n_train: int, n_features: int) -> tuple[torch.Tensor, torch.Tensor]:
        cfg = self.cfg
        generate = rand_dataset_filtered if cfg.filter_unpredictable else rand_dataset_plain
        while True:  # rejection sampling until we get a valid dataset
            n_classes = 0 if self.regression else randint(2, cfg.max_classes + 1)  # 0 = numerical target
            columns = generate(rand_cat_sizes(n_features, cfg.max_cat_size), [n_classes], n_rows)
            x = torch.cat([columns[f"x_{i}"] for i in range(n_features)], dim=-1).float()
            y = columns["y_0"].float().squeeze(-1)
            if not self.regression:
                y = torch.randperm(n_classes)[y.long()].float()  # random label permutation
                row_perm = fix_class_split(y, n_train)
                if row_perm is None:
                    continue
                x, y = x[row_perm], y[row_perm]

            if not (x[:n_train].std(dim=0) > 0).any():  # all features are constant on the training rows
                continue
            x = preprocess(x, n_train)[:, torch.randperm(x.shape[1])]
            if self.regression:
                y = preprocess(y[:, None], n_train).squeeze(-1)
            return x, y


def rand_size(low: int, high: int, log_uniform: bool) -> int:  # random int in [low, high]
    return randlogint(low, high + 1) if log_uniform else int(randint(low, high + 1))


def fix_class_split(y: torch.Tensor, n_train: int, n_attempts: int = 10) -> torch.Tensor | None:
    """Returns a row permutation such that train and test rows contain the same >= 2 classes, or None if none found."""
    perm = torch.arange(len(y))
    for _ in range(n_attempts):
        train_classes, test_classes = torch.unique(y[perm[:n_train]]), torch.unique(y[perm[n_train:]])
        if len(train_classes) >= 2 and torch.equal(train_classes, test_classes):
            return perm
        perm = torch.randperm(len(y))
    return None


def preprocess(x: torch.Tensor, n_fit: int | None = None) -> torch.Tensor:
    """Clips outliers and standardizes each column of x: (n_rows, n_cols) using statistics of the first n_fit rows,
    i.e. the training rows both in the prior and in the scikit-learn interface (n_fit=None uses all rows).
    Columns that are constant on these rows become zero."""
    return standardize(clip_outliers(x, n_fit), n_fit)


def clip_outliers(x: torch.Tensor, n_fit: int | None = None, n_std: float = 4.0) -> torch.Tensor:
    # clamp each column to mean +- n_std * std, where mean and std are re-estimated without the outliers
    ref = x[:n_fit]
    mean, std = ref.mean(dim=0), ref.std(dim=0)
    inlier = torch.where((ref - mean).abs() <= n_std * std, ref, torch.nan)
    mean = inlier.nanmean(dim=0)
    std = (inlier - mean).square().nanmean(dim=0).sqrt()
    return x.clamp(mean - n_std * std, mean + n_std * std)


def standardize(x: torch.Tensor, n_fit: int | None = None, clip: float = 100.0) -> torch.Tensor:
    mean, std = x[:n_fit].mean(dim=0), x[:n_fit].std(dim=0)
    return torch.where(std > 0, (x - mean) / std, 0.0).clamp(-clip, clip)


def iter_batches(cfg: DataConfig, seed: int):
    """Infinite iterator over micro-batches (x, y, n_train) generated by `cfg.num_workers` CPU processes."""
    num_workers = getattr(os, "process_cpu_count", os.cpu_count)() if cfg.num_workers < 0 else cfg.num_workers
    loader = DataLoader(PriorDataset(cfg), batch_size=None, collate_fn=identity, num_workers=num_workers,
                        worker_init_fn=init_worker, generator=torch.Generator().manual_seed(seed))
    return ((torch.from_numpy(x), torch.from_numpy(y), n_train) for x, y, n_train in loader)  # starts the workers


def identity(batch):  # keep numpy arrays as they are (the default collate would convert them to tensors)
    return batch


def init_worker(worker_id: int):
    torch.set_num_threads(1)  # one dataset per process, no intra-op parallelism
    np.random.seed(torch.initial_seed() % 2**32)  # torch is already seeded per worker, numpy is not
